export const ERROR_CODE = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  TOTP_REQUIRED: "TOTP_REQUIRED",
  TOTP_INVALID: "TOTP_INVALID",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  RATE_LIMITED: "RATE_LIMITED",
  REFRESH_TOKEN_REUSED: "REFRESH_TOKEN_REUSED",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  SLOT_CONTENTION: "SLOT_CONTENTION",
  TENANT_SUSPENDED: "TENANT_SUSPENDED",
  CONCURRENCY_LIMIT_REACHED: "CONCURRENCY_LIMIT_REACHED",
  SPEND_LIMIT_REACHED: "SPEND_LIMIT_REACHED",
  CSRF_TOKEN_INVALID: "CSRF_TOKEN_INVALID",
  WEBHOOK_SIGNATURE_INVALID: "WEBHOOK_SIGNATURE_INVALID",
  WEBHOOK_REPLAY_DETECTED: "WEBHOOK_REPLAY_DETECTED",
  PROVIDER_TIMEOUT: "PROVIDER_TIMEOUT",
  PROVIDER_FAILURE: "PROVIDER_FAILURE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
